# Generated by Django 5.2 on 2025-05-04 13:23

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaintractApp', '0002_remove_document_signee_remove_signature_signer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='s3_file_key',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
    ]
